version: "3"
services: 
  postgres:
    image: postgres:9.6
    restart: always
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "users"
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
    - "8080:8080"
    env_file: 
    - ".env"
