CREATE TABLE users (
	id VARCHAR(40) NOT NULL,
	email VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL,
	name VARCHAR(250) NOT NULL,
	role VARCHAR(250) DEFAULT 'user' NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (id),
	CONSTRAINT EMAIL_UNQ UNIQUE (email)
)